name: leet_seung_mo
description: "LEET 성적 오름의 지름길"
publish_to: 'none'
version: 1.0.0+17

environment:
  sdk: ^3.5.3

dependencies:
  async: ^2.11.0
  flutter:
    sdk: flutter
  intl: ^0.19.0
  http: ^1.2.2
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  provider: ^6.1.2
  uuid: ^4.5.1
  flutter_cache_manager: ^3.4.1
  flutter_svg: ^2.0.16
  no_screenshot: ^0.3.1
  firebase_crashlytics: ^4.3.1
  in_app_purchase: ^3.2.1
  in_app_purchase_storekit: ^0.3.21
  cloud_functions: ^5.3.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.svg
